name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-package:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Test FlowStack
        uses: mxcl/xcodebuild@v3
        with:
          platform: iOS
          action: test
          scheme: FlowStack
  build-example-project:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Build FlowStackExample
        uses: mxcl/xcodebuild@v3
        with:
          platform: iOS
          action: build
          workspace: FlowStackExample/FlowStackExample.xcodeproj/project.xcworkspace
          scheme: FlowStackExample
